name = "webicon"
main = "build/worker/shim.mjs"
compatibility_date = "2024-11-28"
routes = [{ pattern = "webicon.ariscript.org", custom_domain = true }]
workers_dev = false

[build]
command = "cargo install -q worker-build && worker-build --release"
